### ISSUE TITLE
Missing Type Name Causing Errors

### ISSUE THREAD

**Issue by s0ulessb0nes** [BirdiePeep/VRCAvatarActions#1]
Just loaded this into Unity 2018.4.20f1, and there is an error that prevents the scripts from running.
"**Assets\VRCAvatarActions-main\Source\BaseActions.cs(182,62): error CS0426: The type name 'ChangeType' does not exist in the type 'VRC_AvatarParameterDriver'**"
I'm not sure how to fix this :(

**Comment by BirdiePeep** [comment]
Looks like you are using an older version of the VRCSDK.  They updated about a month ago, the VRC_AvatarParameterDriver got a number of updates which I had to push changes for.  So to fix you will need to update to the latest VRCSDK.  I'd also recommend making a backup of your project before you do, just to be safe.
https://vrchat.com/home/download
