### ISSUE TITLE
Preserving Existing Expressions Not Working

### ISSUE THREAD

**Issue by TyggzTiger** [BirdiePeep/VRCAvatarActions#3]
I cannot seem to preserve the pre existing expression menu items when selecting Pre-Existing, naming it the same, and building. 

Do you happen to have documentation on how to use this function?
Thank you

**Comment by BirdiePeep** [comment]
Did a few tests here to see if the function was still working as intended, I'm unable to see any issue with my tests.
It should work as simple as you have described it.

Define a menu action of type "Pre-Existing".
The name should match a control defined in the corresponding VRCExpressionsMenu object.
As long as they are the same it shouldn't overwrite or delete that control when you build.

If you have an example of that not working feel free to make a zip and post a dropbox link.  I can take a look and see what might be going on.

**Comment by TyggzTiger** [comment]
Thank you for your response! I will keep trying.
I think the problem I'm having is with preserving a sub menu and the item toggles within the sub menu.
