### ISSUE TITLE
Changing Action Types Leaves Previously Populated Type Active

### ISSUE THREAD

**Issue by abnormalPotassium** [BirdiePeep/VRCAvatarActions#4]
I was trying to figure out why a few of my sliders weren't working and using animations that weren't what I gave it. Turns out if you have something in object properties when type is toggle and then change type to slider it keeps the object properties and combines that with your given animation.

Edit: Also an option to set the default parameter for a bool would be cool

Edit 2: There doesn't seem to be a way to toggle active items off and on either. Base state seems to have to be inactive initially.

**Comment by BirdiePeep** [comment]
Code has been updated with a few things.  The slider fix was necessary.  The other changes below were for my own uses but might go in line with what you were asking.

- Slider code has been fixed to only use the raw animation provided, even when object properties might exist.
- Parameter defaults can be set on the top level VRCAvatarActions script in the options
- Toggle states can be marked as "isOffState".  This means when all other toggles that share the same parameter are off, the system reverts to this state.  Also by default it will be the first state the avatar is on.
