### ISSUE TITLE
Simplify emote creation

### ISSUE THREAD

**Issue by rdragonz** [BirdiePeep/VRCAvatarActions#5]
Create an object to allow for the simplification of adding emotes to your avatar. Ideally it would have a parameter for the animation to play, and the name of the action in the expressions menu.

**Comment by BirdiePeep** [comment]
This is something you can achieve with the current system.  If you want to play an animation, create a menu action of type Button.  Provide it the animation you wish to play, and set a hold time.  This will make sure the animation plays for X seconds even if you release the button.  When it's complete the animation controller will return to a neutral state.

**Comment by rdragonz** [comment]
I am having a hard time with the hold times system. I cannot cancel the emotes using the expressions menu, and my avatar does not return to neutral pose when the hold time finishes.
