### ISSUE TITLE
Index was outside the bounds of the array

### ISSUE THREAD

**Issue by HalfDragonLucy** [BirdiePeep/VRCAvatarActions#6]
VRCAvatarActions.BaseActions.<BuildSetup>g__GetController|26_0 (VRC.SDK3.Avatars.Components.VRCAvatarDescriptor+AnimLayerType animLayerType, System.String name) (at Assets/VRCAvatarActions-main/VRCAvatarActions-main/Source/BaseActions.cs:706)
VRCAvatarActions.BaseActions.BuildSetup () (at Assets/VRCAvatarActions-main/VRCAvatarActions-main/Source/BaseActions.cs:669)
VRCAvatarActions.BaseActions.BuildAvatarData (VRC.SDK3.Avatars.Components.VRCAvatarDescriptor desc, VRCAvatarActions.AvatarActions actionsDesc) (at Assets/VRCAvatarActions-main/VRCAvatarActions-main/Source/BaseActions.cs:655)
VRCAvatarActions.AvatarActionsEditor.InspectorBody () (at Assets/VRCAvatarActions-main/VRCAvatarActions-main/Source/AvatarActions.cs:119)
VRCAvatarActions.AvatarActionsEditor.OnInspectorGUI () (at Assets/VRCAvatarActions-main/VRCAvatarActions-main/Source/AvatarActions.cs:64)
UnityEditor.InspectorWindow.DoOnInspectorGUI (System.Boolean rebuildOptimizedGUIBlock, UnityEditor.Editor editor, System.Boolean wasVisible, UnityEngine.Rect& contentRect) (at C:/buildslave/unity/build/Editor/Mono/Inspector/InspectorWindow.cs:1647)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr) (at C:/buildslave/unity/build/Modules/IMGUI/GUIUtility.cs:179)

**Comment by BirdiePeep** [comment]
This error appears to occur when the AvatarDescriptor lacks data that should be there by default.   It's possible the VRCSDK didn't initialize it correctly or the save data was corrupted.  To fix you will need to use the 'Reset To Default' button on the avatar descriptor under Playable Layers, then try building again.
An error dialog was added to the client in case anyone else encounters this error.

**Comment by HalfDragonLucy** [comment]
Had the problem again and no error dialog was showing up!
